### ISSUE TITLE
Service is crashing when used with OVH public cloud

### ISSUE THREAD

**Issue by acidoxee** [Linaro/openstack-exporter#7]
I don't know if you plan on supporting OpenStack's public cloud with OVH, but it would be great if that were the case.

I'm using your Docker image to deploy a service on a Swarm cluster, with the following file (very simplified and not showing other services):

```yml
version: '3.7'

services:
  openstack_exporter:
    image: quay.io/niedbalski/openstack-exporter:v0.0.7
    configs:
      - source: openstack_exporter
        target: /etc/openstack/clouds.yml
    command: ['default']

configs:
  openstack_exporter:
    external: true
```

The `openstack_exporter` config links to an external Docker config, which is the following:

```yml
clouds:
  default:
    region_name: GRA3
    identity_api_version: 3
    identity_interface: public
    auth:
      username: <redacted>
      password: <redacted>
      project_name: <redacted>
      project_domain_name: 'Default'
      user_domain_name: 'Default'
      auth_url: https://auth.cloud.ovh.net/v3
      verify: false
```

The service always crashes after startup, with the following error:
<details><summary>Container logs</summary>
<p>

```bash
time="2019-05-07T08:42:12Z" level=info msg="Starting openstack exporter (version=, branch=, revision=)" source="main.go:49"
time="2019-05-07T08:42:12Z" level=info msg="Build context (go=go1.11.5, user=, date=)" source="main.go:50"
time="2019-05-07T08:42:12Z" level=info msg="Adding metric: floating_ips to exporter: neutron" source="exporter.go:54"
time="2019-05-07T08:42:12Z" level=info msg="Adding metric: networks to exporter: neutron" source="exporter.go:54"
time="2019-05-07T08:42:12Z" level=info msg="Adding metric: security_groups to exporter: neutron" source="exporter.go:54"
time="2019-05-07T08:42:12Z" level=info msg="Adding metric: subnets to exporter: neutron" source="exporter.go:54"
time="2019-05-07T08:42:12Z" level=info msg="Adding metric: agent_state to exporter: neutron" source="exporter.go:54"
time="2019-05-07T08:42:12Z" level=info msg="Enabled exporter for service: network" source="main.go:68"
time="2019-05-07T08:42:12Z" level=info msg="Adding metric: flavors to exporter: nova" source="exporter.go:54"
time="2019-05-07T08:42:12Z" level=info msg="Adding metric: availability_zones to exporter: nova" source="exporter.go:54"
time="2019-05-07T08:42:12Z" level=info msg="Adding metric: security_groups to exporter: nova" source="exporter.go:54"
time="2019-05-07T08:42:12Z" level=info msg="Adding metric: total_vms to exporter: nova" source="exporter.go:54"
time="2019-05-07T08:42:12Z" level=info msg="Adding metric: running_vms to exporter: nova" source="exporter.go:54"
time="2019-05-07T08:42:12Z" level=info msg="Adding metric: current_workload to exporter: nova" source="exporter.go:54"
time="2019-05-07T08:42:12Z" level=info msg="Adding metric: vcpus_available to exporter: nova" source="exporter.go:54"
time="2019-05-07T08:42:12Z" level=info msg="Adding metric: vcpus_used to exporter: nova" source="exporter.go:54"
time="2019-05-07T08:42:12Z" level=info msg="Adding metric: memory_available_bytes to exporter: nova" source="exporter.go:54"
time="2019-05-07T08:42:12Z" level=info msg="Adding metric: memory_used_bytes to exporter: nova" source="exporter.go:54"
time="2019-05-07T08:42:12Z" level=info msg="Adding metric: local_storage_available_bytes to exporter: nova" source="exporter.go:54"
time="2019-05-07T08:42:12Z" level=info msg="Adding metric: local_storage_used_bytes to exporter: nova" source="exporter.go:54"
time="2019-05-07T08:42:12Z" level=info msg="Adding metric: agent_state to exporter: nova" source="exporter.go:54"
time="2019-05-07T08:42:12Z" level=info msg="Enabled exporter for service: compute" source="main.go:68"
time="2019-05-07T08:42:12Z" level=info msg="Adding metric: images to exporter: glance" source="exporter.go:54"
time="2019-05-07T08:42:12Z" level=info msg="Enabled exporter for service: image" source="main.go:68"
time="2019-05-07T08:42:12Z" level=info msg="Adding metric: volumes to exporter: cinder" source="exporter.go:54"
time="2019-05-07T08:42:12Z" level=info msg="Adding metric: snapshots to exporter: cinder" source="exporter.go:54"
time="2019-05-07T08:42:12Z" level=info msg="Adding metric: agent_state to exporter: cinder" source="exporter.go:54"
time="2019-05-07T08:42:12Z" level=info msg="Enabled exporter for service: volume" source="main.go:68"
time="2019-05-07T08:42:12Z" level=info msg="Adding metric: domains to exporter: identity" source="exporter.go:54"
time="2019-05-07T08:42:12Z" level=info msg="Adding metric: users to exporter: identity" source="exporter.go:54"
time="2019-05-07T08:42:12Z" level=info msg="Adding metric: groups to exporter: identity" source="exporter.go:54"
time="2019-05-07T08:42:12Z" level=info msg="Adding metric: projects to exporter: identity" source="exporter.go:54"
time="2019-05-07T08:42:12Z" level=info msg="Adding metric: regions to exporter: identity" source="exporter.go:54"
time="2019-05-07T08:42:12Z" level=info msg="Enabled exporter for service: identity" source="main.go:68"
time="2019-05-07T08:42:12Z" level=info msg="Starting HTTP server on :9180" source="main.go:83"
time="2019-05-07T08:42:20Z" level=info msg="Fetching list of services" source="nova.go:53"
time="2019-05-07T08:42:20Z" level=info msg="Fetching domains information" source="keystone.go:45"
time="2019-05-07T08:42:20Z" level=info msg="Fetching floating ips list" source="neutron.go:47"
time="2019-05-07T08:42:20Z" level=info msg="Fetching images list" source="glance.go:39"
time="2019-05-07T08:42:20Z" level=info msg="Fetching volumes info" source="cinder.go:54"
time="2019-05-07T08:42:20Z" level=error msg="failed to list domains\ncaused by: Unauthorised URL https://auth.cloud.ovh.net/v3/domains\ncaused by: request (https://auth.cloud.ovh.net/v3/domains) returned unexpected status: 403; error info: Failed: 403 error: You are not authorized to perform the requested action: identity:list_domains." source="keystone.go:48"
time="2019-05-07T08:42:20Z" level=info msg="Fetching users information" source="keystone.go:53"
time="2019-05-07T08:42:20Z" level=error msg="failed to list floating ips\ncaused by: Resource at https://network.compute.gra3.cloud.ovh.net/v2.0/floatingips not found\ncaused by: request (https://network.compute.gra3.cloud.ovh.net/v2.0/floatingips) returned unexpected status: 404; error info: {\"message\": \"The resource could not be found.<br /><br />\\n\\n\\n\", \"code\": \"404 Not Found\", \"title\": \"Not Found\"}" source="neutron.go:50"
time="2019-05-07T08:42:20Z" level=info msg="Fetching agents list" source="neutron.go:53"
time="2019-05-07T08:42:20Z" level=info msg="Fetching services state information" source="cinder.go:60"
time="2019-05-07T08:42:20Z" level=error msg="failed to list users\ncaused by: Unauthorised URL https://auth.cloud.ovh.net/v3/users\ncaused by: request (https://auth.cloud.ovh.net/v3/users) returned unexpected status: 403; error info: Failed: 403 error: You are not authorized to perform the requested action: identity:list_users." source="keystone.go:56"
time="2019-05-07T08:42:20Z" level=info msg="Fetching projects information" source="keystone.go:61"
time="2019-05-07T08:42:20Z" level=error msg="invalid status (403): {\"forbidden\": {\"message\": \"Policy doesn't allow volume_extension:services:index to be performed.\", \"code\": 403}}" source="cinder.go:63"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x82827d]

goroutine 36 [running]:
main.(*CinderExporter).Collect(0xc000056900, 0xc00005a180)
	/app/cinder.go:66 +0x1dd
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
	/app/vendor/github.com/prometheus/client_golang/prometheus/registry.go:434 +0x193
created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
	/app/vendor/github.com/prometheus/client_golang/prometheus/registry.go:526 +0xe23
```
</p>
</details>

Thanks for your time.

**Comment by niedbalski** [comment]
At the moment, the exporter is oriented to be run as an admin tenant and haven't been tested to be run as a non-admin user.

The reason is that some API calls to the OpenStack APIs requires admin privileges. However, I think the issue you are reporting should be fixed in a way on which those metrics are just ignored.

Please check the latest 0.0.8 release and check if this problem still occurs, note that this project has been moved to https://github.com/openstack-exporter/openstack-exporter and report there if you have any issues.

Thanks!
